
diixo = [
    'able', 'al', 'all', 'ally', 'also', 'an', 'and', 'any', 'are', 'as', 'ask', 'be', 'fall',
    'because', 'but',
    'can', 'caus', 'class', 'code', 'come', 'commit', 'common', 'could',
    'day', 'did', 'do', 'doubt', 'down', 'drama', 'draw',
    'each', 'earn', 'ed', 'end', 'equal', 'er', 'es', 'ever', 'every', 'exten',
    'fill', 'fix', 'fore',
    'gather', 'gether', 'good', 'he', 'hear', 'here', 'his',
    'ight', 'ill', 'ing', 'inter', 'is', 'is', 'istic', 'it', 'ity',
    'know', 'learn', 'less', 'load', 'ly',
    'mask', 'may', 'mis', 'more', 'most', 'multi',
    'nation', 'ness', 'never', 'ng', 'no', 'nope', 'not',
    'on', 'or', 'pass', 'post', 'pre', 'pro', 'profession', 'put', 're',
    'real', 'realiz', 'run', 'regard',
    'say', 'seem', 'she', 'should', 'sion', 'size', 'so', 'some', 'soon', 'still', 'stop', 'sub', 'super', 'sect', 'solv', 'sing',
    'task', 'teach', 'than', 'that', 'the', 'then', 'there', 'this', 'tion', 'to', 'too', 'trans', 'type',
    'us', 'use', 'usual',
    'visib', 'visual', 'visit', 'vision',
    'want', 'ward', 'was', 'we', 'wear', 'were', 'when', 'where', 'will', 'would',
    'you', 'young',
    #im, sup, sur (pro, re, gress, fess) 
    'ment', 'ion',
    'access', 'address', 'amass', 'assess', 'brows', 'choos', 'collaps', 'compass', 'compat', 'compos', 'compres', 'confes', 'convers', 'cross',
    'diagnos', 'dis', 'discuss', 'miss', 'dispens', 'dispers', 'dispos', 'regard', 'stress', 'gross', 'expos', 'express', 'guess', 'possib',
    'spect', 'licens', 'los', 'mess', 'opposs', 'pars', 'press', 'process', 'profess', 'progress', 'regress', 'propos', 'purpos', 'vers', 'sens',
    'sing', 'stress',
    'key', 'word', 'form', 'base', 'inform', 'ativ', 'present', 'oper', 'open', 'norm', 'relat', 'auto', 'launch',
    'object', 'coord', 'cover', 'nomi', 'pack', 'part', 'poly', 'count', 'direct', 'master', 'organ', 'order', 'over',
    'bio', 'cyber', 'tech', 'anti', 'logic', 'atic', 'deep', 'space', 'sport', 'cycl',
    'free', 'ship', 'graph', 'own', 'photo', 'freez', 'slow', 'show', 'grow',
    'hyper', 'hash', 'gram', 'hard', 'lexic', 'orth',
    'project', 'program', 'param', 'phone', 'tele', 'power', 'excel', 'cell', 'produc', 'extra', 'extract', 'extrapolat', 'cancel',
    'micro', 'head', 'chip', 'mobil', 'system', 'control', 'comput', 'struct', 'view', 'bench', 'board', 'client', 'video',
    'web', 'assembl', 'develop', 'work', 'design', 'thought',
    'round', 'around', 'flow', 'sheet', 'time', 'shop', 'group', 'local', 'ground', 'stack', 'sketch', 'sentiment', 'life',
    'with', 'through', 'rout', 'stand', 'shout', 'routine', 'scout', 'roll', 'perform', 'bound', 'look', 'scroll', 'standard', 'break',
    #'out', often, turn, point, upper, low, fall, non, none, nope
    'back', 'switch', 'throw', 'trac', 'track', 'tract', 'author', 'determin', 'detect', 'desir',
    'distract', 'distort', 'distinguish', 'distinct', 'clos', 'clon', 'mark', 'market', 'land', 'crypt', 'engine', 'featur', 'cach', 'memor',
    #'abnormal', 'accident', 'actual', 'algorithm', 'alphabet', 'analytic', 'algebra',
    #'call', 'ic', #??? #, 'ous',
    'allegor', 'alleviat', 'alleg', 'allocat', 'admin', 'admir', 'allot', 'allow', 'allud', 'allus', 'exam', 'examin', 'exampl', 'alli',
    'mail', 'magic', 'basic', 'mechanic', 'medic', 'mimic', 'mini',
    'atomic', 'generic', 'basic', 'graphic', 'organic', 'empir', 'epic', 'optic', 'entropic', 'economic', 'dynamic', 'electr',
    'electron', 'entrop', 'fantast', 'hypoth', 'lexic', 'ident', 'algebra', 'algorithm', 'alphabet', 'analytic',
    'arithmet', 'asymptot', 'typic', 'semantic', 'specif', 'strateg', 'synthet', 'vocal', 'pract', 'public', 'topic',
    'vertic', 'numer', 'paradox', 'optimist', 'monolith', 'reciproc', 'scien', 'synonym', 'critic', 'ellip', 'drastic', 'extrinsic',
    'phonet', 'physic', 'monoton', 'suspic', 'suffic', 'stratif', 'stochast', 'stick', 'splic', 'spher', 'spars', 'sophisticat',
    'complicat', 'predict', 'offic', 'strict', 'ficat', 'twice', 'trick', 'traff', 'tick', 'thick', 'theor', 'communic', 'symbol',
    'solicit', 'small', 'smart', 'devic', 'certif', 'atmo', 'amplif', 'clarif', 'classif', 'codif', 'dens', 'densif', 'diversif',
    'electrif', 'gamif', 'gratif', 'identif', 'justif', 'minif', 'modif', 'mortif', 'notif', 'qualif', 'quantif', 'simplif', 'unif',
    'verif', 'notic', 'pric', 'voic', 'which', 'academ', 'addict', 'advic', 'alpha', 'logic', 'trop', 'applic', 'artic', 'artific',
    'authent', 'centr', 'bion', 'canon', 'categor', 'click', 'hapt', 'servic', 'coeff', 'conflict', 'contradict', 'convict',
    'dedicat', 'dupl', 'defic', 'delic', 'dict', 'dictat', 'difficult', 'effic', 'electr', 'magnet', 'elicit', 'ergonom', 'evict',
    'explic', 'felic', 'flick', 'harmon', 'hierarch', 'acoust', 'amplic', 'analog', 'elastic', 'fabric', 'histor', 'plast',
    'indic', 'indicat', 'inflict', 'intrinsic', 'logarithm', 'magnif', 'malic', 'metaphor', 'method', 'music', 'period', 'philosoph',
    'polit', 'polic', 'morph', 'python', 'quick', 'joic', 'replic', 'ridic', 'rubric', 'robo', 'scept', 'colon', 'skept', 'simplic',
    'vehic', 'variad', 'vindic', 'judic', 'benefic', 'choic', 'combin', 'energ', 'intric', 'justic', 'partic', 'predica', 'profic',
    'radic', 'robust', 'modal', 'thing', 'cloth', 'breath', 'smooth', 'sooth', 'serv', 'reserv', 'observ', 'server', 'user', 'squar',
    #'pick', 'kick', 'sick', 'slic', 'wick', 'uni', 'mnemo', 'nice', 'nich',
    'portion', 'calcul', 'synth', 'simpl', 'suppl', 'tact', 'tactic', 'vict', 'vici', 'contact', 'synt', 'silicon', 'icon', 'respon',
    'conduct', 'semi', 'seminat', 'matrix', 'matric', 'data', 'meta', 'wiki', 'manag', 'grid', 'link', 'blink', 'loop', 'media', 'resolv',
    'swear', 'googl', 'forswear', 'rich', 'acquir', 'enquir', 'inquir', 'acquit', 'equit', 'equip', 'oblig', 'obliquity', 'equat', 'adequat',
    'check', 'defin', 'script', 'friend', 'reque', 'scop', 'frequen', 'infra', 'shell', 'sheet', 'action', 'activ', 'diffus', 'satisf',
    'requir', 'diff', 'screen', 'touch', 'full', 'beaut', 'delight', 'faith', 'fright', 'fruit', 'sorrow', 'thank', 'succe', 'differ',
    'wild', 'wonder', 'wrong', 'respect', 'skill', 'mind', 'pain', 'paint', 'resolut', 'though', 'thorough', 'scrib', 'soft', 'sort',
    'paper', 'white', 'wall', 'next', 'letter', 'need', 'prim', 'necess', 'print', 'test', 'tessellat', 'sweet', 'sweep', 'prepar', 'quir',
    'quit', 'equi', 'probab', 'proper',
    'vocat', 'valen', 'valenc', 'valent', 'pict', 'pictur', 'varianc', 'variat', 'variant', 'variabl', 'variad', 'varie', 'vary', 'various',
    'identif', 'univers', 'commun', 'unix', 'unit', 'unity', 'union', 'unique', 'interpolat', 'inten', 'operat', 'opinion', 'intern',
    'cool', 'cook', 'book', 'bool', 'ultra', 'fast', 'text', 'context', 'contest', 'content', 'face', 'hand', 'edit', 'circl', 'center',
    'expedit', 'expend', 'expedien', 'educat', 'constrain', 'conscious', 'connect', 'continu', 'expens', 'conjunct', 'expect', 'experienc',
    'effect', 'expans', 'expedite', 'explor', 'command', 'confirm', 'except', 'expir', 'explain', 'explanat', 'follow', 'cluster', 'collect',
    'node', 'expand', 'excess', 'expert', 'chang', 'champ', 'channel', 'iterat', 'chanc', 'challeng', 'chapt', 'excit', 'recogni', 'fold',
    'charg', 'chart', 'clock', 'focus', 'call', 'ic', 'consist', 'optim', 'permut', 'flect', 'simpl', 'help', 'forward', 'feed',
    'sight', 'sign', 'mono', 'assist', 'assign', 'insight', 'consider', 'associat', 'foresee', 'start', 'xor', 'debug', 'metr',
    'unifi', 'unicorn', 'unicode', 'jump', 'quiet', 'stream', 'ignit', 'fuck', 'guarant', 'digit', 'ignor', 'main', 'remain', 'maintain',
    'mainfram', 'mainten', 'domain', 'document', 'debut', 'debat', 'crowd', 'depend', 'doc', 'found', 'dock', 'funder', 'thunder',
    'pseudo', 'depict', 'depart', 'department', 'fund', 'fundament', 'sampl', 'doctrin', 'blund', 'requi', 'same', 'inert',
    'etern', 'achiev', 'adapt', 'afford', 'approach', 'attain', 'attack', 'avail', 'ability', 'capab', 'compar', 'component', 'puls',
    'contriv', 'custom', 'detain', 'embed', 'embar', 'exec', 'idea', 'ideal', 'migrat', 'accur', 'index', 'inspir', 'measur', 'must', 'www',
    'profil', 'profit', 'reach', 'read', 'cours', 'relevan', 'remot', 'remov', 'repeat', 'specif', 'separ', 'stabil', 'suggest', 'suit', 'sql',
    'sustain', 'swap', 'train', 'void', 'avoid', 'pool', 'variab', 'thesis', 'thread', 'spool', 'accept', 'viab', 'spoon', 'spoof', 'accent',
    'detail', 'attach', 'attempt', 'audit', 'audio', 'attend', 'augment', 'install', 'attent', 'insert', 'stor', 'strain', 'prob', 'seque',
    'compan', 'promis', 'contribut', 'coupl', 'curv', 'promot', 'concern', 'compact', 'concept', 'config', 'construct', 'consult', 'consum',
    'react', 'activat', 'sourc', 'dead', 'sound', 'lock', 'push', 'front', 'block', 'caps', 'capital', 'flock', 'float', 'strap', 'brand',
    'capsul', 'locat', 'spill', 'spin', 'flood', 'blog', 'capacit', 'flip', 'deal', 'cast', 'bias', 'balanc', 'born', 'border', 'borrow',
    'from', 'posit', 'repositor', 'transpos', 'positiv', 'transport', 'suppos', 'support', 'report', 'apprais', 'appoint', 'disappoint',
    'deposit', 'deprecat', 'deploy', 'const', 'constit', 'conven', 'convent', 'convenien', 'corpora', 'converg', 'bind', 'boot', 'believ',
    'belief', 'stub', 'stuck', 'band', 'bell', 'belong', 'broad', 'abbreviat', 'struggl', 'label', 'abandon', 'luck', 'happ', 'health',
    'hurt', 'hush', 'quer', 'problem', 'releas', 'arrang', 'array', 'appear', 'reason', 'appeal', 'rotat', 'arriv', 'receiv', 'parent',
    'quest', 'question', 'quot', 'publ', 'proof', 'protect', 'queu', 'propagat', 'depth', 'protest', 'buf', 'proto', 'bug', 'prototyp',
    'protocol', 'thus', 'thumb', 'obsess', 'obsolet', 'potent', 'origin', 'orient', 'pix', 'pivot', 'mega', 'intel', 'interest', 'pull',
    'compil', 'recommend', 'conceiv', 'point', 'complet', 'null', 'complex', 'trust', 'search', 'condit', 'rescu', 'select', 'self', 'selv',
    'them', 'serial', 'segment', 'their', 'series', 'serious', 'segregat', 'aggregat', 'aggress', 'quad', 'random', 'strang', 'spot', 'rang',
    'sprang', 'straight', 'lagrang', 'fresh', 'after', 'updat', 'about', 'befor', 'abound', 'mention', 'abort', 'above', 'seam', 'fetch',
    'prefer', 'refer', 'hang', 'heap', 'cheap', 'chat', 'cheat', 'regulat', 'occur', 'regular', 'caption', 'captur', 'captivat', 'capt',
    'card', 'cardinal', 'discard', 'discover', 'discret', 'discrep', 'discriminat', 'discriminant', 'courag', 'renovat', 'revolut', 'reward',
    'error', 'step', 'stamp', 'stereo', 'append', 'apprecia', 'apprehen', 'proxim', 'approv', 'appropriat', 'advert', 'advis',
    'admiss', 'admit', 'just', 'adjust', 'join', 'adjoin', 'disjoin', 'junct', 'reject', 'inject', 'commut', 'complai', 'represent', 'align',
    'func', 'absen', 'essen', 'consent', 'assert', 'establish', 'static', 'absolut', 'complement', 'mean', 'scor', 'accelerat',
    'under', 'understand', 'understood', 'graduat', 'deserv', 'deliver', 'declar', 'decid', 'damag', 'decept', 'concatenat', 'acced', 'abus',
    'clean', 'cloud', 'daemon', 'kick', 'kill', 'incident', 'improv', 'eviden', 'emphas', 'emphat', 'confid', 'business', 'draft', 'facilit',
    'entr', 'entrop', 'entre', 'preneur', 'entrance', 'entrant', 'entrench', 'entreat', 'entrain', 'enter', 'entertain', 'enterpris',
    'accident', 'redundan', 'ready', 'already', 'affirm', 'reduc', 'refus', 'generat', 'region', 'regist', 'implement', 'implicit', 'implicat',
    'implant', 'import', 'impress', 'pronoun', 'prompt', 'reflex', 'refin', 'regret', 'format', 'formul', 'schedul', 'fragment',
    'fract', 'fraction', 'schem', 'scholar', 'secur', 'sensor', 'sentenc', 'sharp', 'shard', 'session', 'singular', 'singl', 'sinus', 'sister',
    'skeleton', 'slight', 'watch', 'smash', 'socket', 'social', 'summit', 'trend', 'trial', 'triang', 'water', 'scenar', 'societ', 'init',
    'finish', 'finit', 'affiliat', 'infer', 'finger', 'affect', 'affin', 'infect', 'financ', 'fine', 'confin', 'currenc', 'current', 'concurr',
    'concret', 'liter', 'curious', 'recur', 'obscur', 'translat', 'rectif', 'transit', 'recurs', 'transcrib', 'transist', 'resist',
    'resilien', 'silen', 'silhouett', 'resid', 'resident', 'resonat', 'restor', 'restart', 'restat', 'restrict', 'restruct', 'submit',
    'restaurant', 'rest', 'fair', 'purchas', 'restrain', 'exploit', 'affab', 'fail', 'explod', 'result', 'resum', 'resurrect', 'host', 'grab',
    'ghost', 'hospit', 'hook', 'ordinar', 'imag', 'absorb', 'climb', 'describ', 'descen', 'condens', 'deriv', 'binanc', 'disturb', 'glob',
    'sell', 'bestow', 'best', 'beta', 'echo', 'semaphor', 'shot', 'shoot', 'short', 'screw', 'turn', 'truth', 'try', 'geo', 'sympath',
    'advanc', 'advantag', 'isolat', 'adventur', 'adorn', 'gestur', 'shift', 'shock', 'shin', 'snap', 'diminish', 'dimens', 'embod',
    'ember', 'emblem', 'deceiv', 'member', 'embrac', 'melod', 'embellish', 'emerg', 'contain', 'novel', 'novic', 'tool', 'toggl', 'token',
    'transfer', 'travel', 'travers', 'triumph', 'trivial', 'trigger', 'trim', 'troubl', 'warn', 'warm', 'warp', 'tell', 'weird', 'craft',
    'crack', 'weigh', 'weight', 'welcom', 'crash', 'bing', 'bin', 'bill', 'angl', 'boil', 'bundl', 'celebrat', 'clip', 'compensat', 'cultur',
    'consol', 'counsel', 'crawl', 'culminat', 'cull', 'storag', 'creat', 'dangl', 'spoil', 'doubl', 'dwell', 'eclips', 'ecma', 'enabl',
    'ensembl', 'tangl', 'fellow', 'gambl', 'handl', 'middl', 'model', 'modem', 'prevail', 'rambl', 'conciliat', 'recruit', 'shuffl', 'retail',
    'scrambl', 'stumbl', 'tackl', 'trail', 'trembl', 'unveil', 'cultivat', 'danger', 'engag', 'ecolog', 'emulat', 'entail', 'moderat',
    # 'shad', 'fell', 'fli', 'tang', 'tile, ->'ling', night, rect+angl, 'empt', area, ling
    'commerc', 'modern', 'comment', 'comfort', 'styl', 'stupid', 'stump', 'stun', 'instant', 'instanc', 'escalat', 'elevat', 'event',
    'evok', 'evolut', 'evolv', 'exact', 'excus', 'devolv', 'exclusiv', 'execut', 'exempl', 'escap', 'even', 'eval', 'estima', 'evening',
    'element', 'retriev', 'retro', 'field', 'solid', 'feel', 'till', 'distill', 'tilt', 'disabl', 'spoil', 'tunel', 'box', 'virtual',
    'list', 'limit', 'black', 'wait', 'liquidat', 'drop', 'lift', 'enlarg', 'enjoy', 'enhanc', 'fool', 'rectang', 'night', 'right',
    'bright', 'wright', 'brief', 'offer', 'coffee', 'exist', 'argument', 'fact', 'manual', 'manufactur', 'factor', 'refactor', 'manipul',
    'fear', 'feasib', 'experiment', 'export', 'desert', 'exponent', 'expound', 'explos', 'argue', 'greet', 'great', 'trade', 'half',
    'govern', 'goal', 'general', 'futur', 'further', 'fork', 'font', 'eras', 'epoch', 'episod', 'camera', 'kernel', 'keep', 'campaign',
    'eliminat', 'effort', 'eigen', 'eject', 'elaborat', 'elect', 'descript', 'degree', 'elaps', 'employ', 'envelop', 'environ', 'exceed',
    'delay', 'delet', 'delegat', 'definit', 'deliberat', 'demonstra', 'mystif', 'depreciate', 'eligib', 'elegan', 'house', 'room', 'root',
    'divers', 'diverg', 'divid', 'docker', 'dominat', 'donat', 'door', 'doom', 'camp', 'campus', 'dominan', 'boost', 'enthusiast',
    'perfect', 'person', 'perspectiv', 'persist', 'persuad', 'inherit', 'innovat', 'inspect', 'offenc', 'offens', 'offend', 'often',
    'actual', 'actuat', 'character', 'impact', 'redact', 'satellit', 'syntax', 'tranquil', 'transact', 'trajector', 'trait', 'transceiv',
    'insinuat', 'transcend', 'transclud', 'txt', 'twitter', 'tweet', 'two', 'network', 'neur', 'modul', 'twitch', 'twink', 'twin',
    'mount', 'mistake', 'moment', 'ascend', 'mountain', 'maintain', 'motiv', 'approximat', 'approb', 'motion', 'emotion', 'deform',
    'nom', 'mouse', 'merg', 'mesh', 'among', 'demand', 'match', 'amount', 'phenomen', 'gnome', 'default', 'defect', 'defeat', 'defer',
    'commiss', 'dismiss', 'emiss', 'intermiss', 'permiss', 'remiss', 'submiss', 'permanent', 'permit', 'permeat', 'defenc', 'defens',
    'defend', 'deflect', 'deflat', 'entire', 'discord', 'either', 'twiddl', 'neighbo', 'neither', 'negotiat', 'neglig', 'neglect', #'sync'
    'negativ', 'render', 'surrender', 'surround', 'surpris', 'suspend', 'surrogate', 'suspect', 'survey', 'suspens', 'surviv',# 'con'
    'deft', 'obfuscat', 'confus', 'infus', 'congrat', 'congest', 'defus', 'infring', 'degrad', 'tensor', 'privileg', 'privat', #privacy
    'tend', 'tender', 'pretend', 'tens', 'pretens', 'pretenc', 'contend', 'contempt', 'contemplat', 'contemp', 'prior', 'threat',
    'depress', 'depriv', 'three', 'depreciat', 'tendenc', 'anonym', 'anomal', 'annual', 'mother', 'brother', 'annoy', 'announc',
    'chain', 'certain', 'annotat', 'ambig', 'amazon', 'ambit', 'anneal', 'answer', 'afraid', 'amaz', 'ultimat', 'tweak', 'tutor',
    'tunnel', 'anim', 'reanimat', 'world', 'hello', 'analys', 'analyz', 'anchor', 'ancient', 'desk', 'correct', 'tree', 'math',
    'street', 'plot', 'material', 'imitat', 'tupl', 'imbue', 'immediat', 'immens', 'popular', 'pleas', 'populat', 'precedent',
    'menu', 'mentor', 'duck', 'dump', 'preced', 'cautio', 'dual', 'gradual', 'grad', 'upgrad', 'gradat', 'gradient', 'gradl',
    'fluctuat', 'fluen', 'fluff', 'conform', 'complian', 'flourish', 'flush', 'impertinen', 'imped', 'impend', 'impel', 'immut',
    'immers', 'imminent', 'migrat', 'industr', 'indulg', 'induct', 'induc', 'individual', 'disput', 'indent', 'incubat', 'increment',
    'decreas', 'increas', 'incredibl', 'height', 'spat', 'final', 'filt', 'involv', 'invok', 'laugh', 'legal', 'legitim',
    'lesson', 'level', 'leverag', 'length', 'lemma', 'layer', 'play', 'splay', 'pilot', 'patch', 'platform', 'team', 'patent',
    'autonom', 'steep', 'pair', 'parallel', 'pardon', 'phras', 'passiv', 'repetit', 'php', 'storm', 'brain', 'branch', 'batch',
    'batter', 'replac', 'famil', 'battle', 'bayes', 'false', 'exult', 'extrem', 'extern', 'exterior', 'devot', 'dexter',
    # other
    #set, heal, repo, side, rand, mov, def, nom-nomo, uous
    #act, bas, log,
    #url, exe, ecut, net, non, sum, go, act, add, app, off, plac, tun, set,
    ]

#print(sorted(diixo))