
diixo = [
    'able', 'al', 'all', 'ally', 'also', 'an', 'and', 'any', 'are', 'as', 'ask', 'be', 'fall',
    'because', 'but',
    'can', 'caus', 'class', 'code', 'come', 'commit', 'common', 'could',
    'day', 'did', 'do', 'doubt', 'down', 'drama', 'draw',
    'each', 'earn', 'ed', 'end', 'equal', 'er', 'es', 'ever', 'every', 'exten',
    'fill', 'fix', 'fore',
    'gather', 'gether', 'good', 'he', 'hear', 'here', 'his',
    'ight', 'ill', 'ing', 'inter', 'is', 'is', 'istic', 'it', 'ity',
    'know', 'learn', 'less', 'load', 'ly',
    'mask', 'may', 'mis', 'more', 'most', 'multi',
    'nation', 'ness', 'never', 'ng', 'no', 'nope', 'not',
    'on', 'or', 'pass', 'post', 'pre', 'pro', 'profession', 'put', 're',
    'real', 'realiz', 'run', 'regard',
    'say', 'seem', 'she', 'should', 'sion', 'size', 'so', 'some', 'soon', 'still', 'stop', 'sub', 'super', 'sect', 'solv', 'sing',
    'task', 'teach', 'than', 'that', 'the', 'then', 'there', 'this', 'tion', 'to', 'too', 'trans', 'type',
    'us', 'use', 'usual',
    'visib', 'visual', 'visit', 'vision',
    'want', 'ward', 'was', 'we', 'wear', 'were', 'when', 'where', 'will', 'would',
    'you', 'young',
    #im, sup, sur (pro, re, gress, fess) 
    'ment', 'ion',
    'access', 'address', 'amass', 'assess', 'brows', 'choos', 'collaps', 'compass', 'compat', 'compos', 'compres', 'confes', 'convers', 'cross',
    'diagnos', 'dis', 'discuss', 'miss', 'dispens', 'dispers', 'dispos', 'regard', 'stress', 'gross', 'expos', 'express', 'guess', 'possib',
    'spect', 'licens', 'los', 'mess', 'opposs', 'pars', 'press', 'process', 'profess', 'progress', 'regress', 'propos', 'purpos', 'vers', 'sens',
    'sing', 'stress',
    'key', 'word', 'form', 'base', 'inform', 'ativ', 'present', 'oper', 'open', 'norm', 'relat', 'auto', 'launch',
    'object', 'coordinat', 'cover', 'nomi', 'pack', 'part', 'poly', 'count', 'direct', 'master', 'organiz', 'order', 'over',
    'bio', 'cyber', 'tech', 'anti', 'logic', 'atic', 'deep', 'space', 'sport', 'cycl',
    'free', 'ship', 'graph', 'own', 'photo', 'freez', 'slow', 'show', 'grow',
    'hyper', 'hash', 'gram', 'hard', 'lexic', 'ortho',
    'project', 'program', 'param', 'phone', 'tele', 'pow', 'excel', 'cell', 'produc', 'extra', 'extract', 'extrapolat', 'cancel',
    'micro', 'head', 'chip', 'mobil', 'system', 'control', 'comput', 'struct', 'view', 'bench', 'board', 'client', 'video',
    'web', 'assembl', 'develop', 'work', 'design', 'thought',
    'round', 'around', 'flow', 'sheet', 'time', 'shop', 'group', 'local', 'ground', 'stack', 'sketch', 'sentiment', 'life',
    'with', 'through', 'rout', 'stand', 'shout', 'routine', 'scout', 'roll', 'perform', 'bound', 'look', 'scroll', 'standard', 'break',
    #'out', often, turn, point, upper, low, fall, non, none, nope
    'back', 'switch', 'throw', 'trac', 'track', 'tract', 'author', 'determin', 'detect', 'desir', 'cach', 'memor',
    'distract', 'distort', 'distinguish', 'distinct', 'clos', 'clon', 'mark', 'market', 'land', 'crypt', 'engine', 'featur',
    #'abnormal', 'accident', 'actual', 'algorithm', 'alphabet', 'analytic', 'algebra',
    #'call', 'ic', #??? #, 'ous',
    'allegor', 'alleviat', 'alleg', 'allocat', 'admin', 'admir', 'allot', 'allow', 'allud', 'allus', 'exam', 'examin', 'exampl', 'alli',
    'mail', 'magic', 'basic', 'mechanic', 'medic', 'mimic', 'mini',
    'atom', 'generic', 'graphic', 'organic', 'empir', 'epic', 'optic', 'entropic', 'econom', 'dynam', 'electr',
    'electron', 'entrop', 'fantas', 'hypoth', 'lexic', 'ident', 'algebra', 'algorithm', 'alphabet', 'analytic',
    'arithmet', 'asymptot', 'typic', 'semantic', 'specif', 'strateg', 'synthet', 'vocal', 'pract', 'public', 'topic',
    'vertic', 'numer', 'paradox', 'optimis', 'monolith', 'reciproc', 'scien', 'synonym', 'critic', 'ellip', 'drastic', 'extrinsic',
    'phonet', 'physic', 'monoton', 'suspic', 'suffic', 'stratif', 'stochast', 'stick', 'splic', 'spher', 'spars', 'sophisticat',
    'complicat', 'predict', 'offic', 'strict', 'ficat', 'twice', 'trick', 'traff', 'tick', 'thick', 'theor', 'communic', 'symbol',
    'solicit', 'small', 'smart', 'devic', 'certif', 'atmo', 'amplif', 'clarif', 'classif', 'codif', 'dens', 'densif', 'diversif',
    'electrif', 'gamif', 'gratif', 'identif', 'justif', 'minif', 'modif', 'mortif', 'notif', 'quali', 'quantif', 'simplif', 'unif',
    'verif', 'notic', 'pric', 'voic', 'which', 'academ', 'addict', 'advic', 'alpha', 'logic', 'trop', 'applic', 'articl', 'ticket',
    'authent', 'centr', 'bion', 'canonical', 'categor', 'click', 'hapt', 'servic', 'coefficient', 'conflict', 'contradict', 'convict',
    'dedicat', 'dupl', 'defic', 'delic', 'dict', 'dictat', 'difficult', 'effic', 'electr', 'magnet', 'elicit', 'ergonom', 'evict',
    'explic', 'felic', 'flick', 'harmon', 'hierarch', 'acoust', 'amplic', 'analog', 'elastic', 'fabric', 'histor', 'plast',
    'indic', 'indicat', 'inflict', 'intrinsic', 'logarithm', 'magnif', 'malic', 'metaphor', 'method', 'music', 'period', 'philosoph',
    'polit', 'polic', 'morph', 'python', 'quick', 'joic', 'replic', 'ridicul', 'rubric', 'robo', 'scept', 'colon', 'skept', 'simplic',
    'vehicl', 'variad', 'vindic', 'judic', 'benefic', 'choic', 'combin', 'energ', 'intric', 'justic', 'particl', 'predica', 'profic',
    'radic', 'robust', 'modal', 'thing', 'cloth', 'breath', 'smooth', 'sooth', 'serv', 'reserv', 'observ', 'server', 'user', 'squar',
    #'pick', 'kick', 'sick', 'slic', 'wick', 'uni', 'mnemo', 'nice', 'nich',
    'portion', 'calcul', 'synth', 'simpl', 'suppl', 'tact', 'tactic', 'vict', 'vici', 'contact', 'synt', 'silicon', 'icon', 'respon',
    'conduct', 'semi', 'seminat', 'matrix', 'matric', 'data', 'meta', 'wiki', 'manag', 'grid', 'link', 'blink', 'loop', 'media', 'resolv',
    'swear', 'googl', 'forswear', 'rich', 'acquir', 'enquir', 'inquir', 'acquit', 'equit', 'equip', 'oblig', 'obliquity', 'equat', 'adequat',
    'check', 'defin', 'script', 'friend', 'reque', 'scop', 'frequen', 'infra', 'shell', 'sheet', 'action', 'activ', 'diffus', 'satisf',
    'requir', 'diff', 'screen', 'touch', 'full', 'beaut', 'delight', 'faith', 'fright', 'fruit', 'sorrow', 'thank', 'succe', 'differ',
    'wild', 'wonder', 'wrong', 'respect', 'skill', 'mind', 'pain', 'paint', 'resolut', 'though', 'thorough', 'scrib', 'soft', 'sort',
    'paper', 'white', 'wall', 'next', 'letter', 'need', 'prim', 'necess', 'print', 'test', 'tessellat', 'sweet', 'sweep', 'prepar', 'quir',
    'quit', 'equi', 'probab', 'proper',
    'vocat', 'valen', 'valenc', 'valent', 'pict', 'pictur', 'varianc', 'variat', 'variant', 'variabl', 'variad', 'varie', 'vary', 'various',
    'identif', 'univers', 'commun', 'unix', 'unit', 'unity', 'union', 'unique', 'interpolat', 'inten', 'operat', 'opinion', 'intern',
    'cool', 'cook', 'book', 'bool', 'ultra', 'fast', 'text', 'context', 'contest', 'content', 'face', 'hand', 'edit', 'circl', 'center',
    'expedit', 'expend', 'expedien', 'educat', 'constrain', 'conscious', 'connect', 'continu', 'expens', 'conjunct', 'expect', 'experien',
    'effect', 'expans', 'expedite', 'explor', 'command', 'confirm', 'except', 'expir', 'explain', 'explanat', 'follow', 'cluster', 'collect',
    'node', 'expand', 'excess', 'expert', 'chang', 'champ', 'channel', 'itera', 'chanc', 'challeng', 'chapt', 'excit', 'recogni', 'fold',
    'charg', 'chart', 'clock', 'focus', 'call', 'ic', 'consist', 'optim', 'permut', 'flect', 'simpl', 'help', 'forward', 'feed',
    'sight', 'sign', 'mono', 'assist', 'assign', 'insight', 'consider', 'foresee', 'start', 'xor', 'debug', 'metr',
    'unifi', 'unicorn', 'unicode', 'jump', 'quiet', 'stream', 'ignit', 'fuck', 'guarante', 'digit', 'ignor', 'main', 'remain',
    'mainfram', 'mainten', 'domain', 'document', 'debut', 'debat', 'crowd', 'depend', 'doc', 'found', 'dock', 'funder', 'thunder',
    'pseudo', 'depict', 'depart', 'department', 'fund', 'fundament', 'sampl', 'doctrin', 'blund', 'requi', 'same', 'inert', 'maintain',
    'etern', 'achiev', 'adapt', 'afford', 'approach', 'attain', 'attack', 'avail', 'ability', 'capab', 'compar', 'component', 'puls',
    'contriv', 'custom', 'detain', 'embed', 'embark', 'exec', 'idea', 'ideal', 'migrat', 'accur', 'index', 'inspir', 'measur', 'must', 'www',
    'profil', 'profit', 'reach', 'read', 'cours', 'relevan', 'remot', 'remov', 'repeat', 'specif', 'separ', 'stabil', 'suggest', 'suit', 'sql',
    'sustain', 'swap', 'train', 'void', 'avoid', 'pool', 'variab', 'thesis', 'thread', 'spool', 'accept', 'viab', 'spoon', 'spoof', 'accent',
    'detail', 'attach', 'attempt', 'audit', 'audio', 'attend', 'augment', 'install', 'attent', 'insert', 'stor', 'strain', 'prob', 'seque',
    'compan', 'promis', 'contribut', 'coupl', 'curv', 'promot', 'concern', 'compact', 'concept', 'config', 'construct', 'consult', 'consum',
    'react', 'activat', 'sourc', 'dead', 'sound', 'lock', 'push', 'front', 'block', 'caps', 'capital', 'flock', 'float', 'strap', 'brand',
    'capsul', 'locat', 'spill', 'spin', 'flood', 'blog', 'capacit', 'flip', 'deal', 'cast', 'bias', 'balanc', 'born', 'border', 'borrow',
    'from', 'posit', 'repositor', 'transpos', 'positiv', 'transport', 'suppos', 'support', 'report', 'apprais', 'appoint', 'disappoint',
    'deposit', 'deprecat', 'deploy', 'const', 'constit', 'conven', 'convent', 'convenien', 'corpora', 'converg', 'bind', 'boot', 'believ',
    'belief', 'stub', 'stuck', 'band', 'bell', 'belong', 'broad', 'abbreviat', 'struggl', 'label', 'abandon', 'luck', 'happ', 'health',
    'hurt', 'hush', 'quer', 'problem', 'releas', 'arrang', 'array', 'appear', 'reason', 'appeal', 'rotat', 'arriv', 'receiv', 'parent',
    'quest', 'question', 'quot', 'publ', 'proof', 'protect', 'queu', 'propagat', 'depth', 'protest', 'buf', 'proto', 'bug', 'prototyp',
    'protocol', 'thus', 'thumb', 'obsess', 'obsolet', 'potent', 'origin', 'orient', 'pix', 'pivot', 'mega', 'intel', 'interest', 'pull',
    'compil', 'recommend', 'conceiv', 'point', 'complet', 'null', 'complex', 'trust', 'search', 'condit', 'rescu', 'select', 'self', 'selv',
    'them', 'serial', 'segment', 'their', 'series', 'serious', 'segregat', 'aggregat', 'aggress', 'quad', 'random', 'strang', 'spot', 'rang',
    'sprang', 'straight', 'lagrang', 'fresh', 'after', 'updat', 'about', 'befor', 'abound', 'mention', 'abort', 'above', 'seam', 'fetch',
    'prefer', 'refer', 'hang', 'heap', 'cheap', 'chat', 'cheat', 'regulat', 'occur', 'regular', 'caption', 'captur', 'captivat', 'capt',
    'card', 'cardinal', 'discard', 'discover', 'discret', 'discrep', 'discriminat', 'discriminant', 'courag', 'renovat', 'revolut', 'reward',
    'error', 'step', 'stamp', 'stereo', 'append', 'apprecia', 'apprehen', 'proxim', 'approv', 'appropriat', 'advert', 'advis',
    'admiss', 'admit', 'just', 'adjust', 'join', 'adjoin', 'disjoin', 'junct', 'reject', 'inject', 'commut', 'complai', 'represent', 'align',
    'func', 'absen', 'essen', 'consent', 'assert', 'establish', 'static', 'absolut', 'complement', 'mean', 'scor', 'accelerat',
    'under', 'understand', 'understood', 'graduat', 'deserv', 'deliver', 'declar', 'decid', 'damag', 'decept', 'concatenat', 'acced', 'abus',
    'clean', 'cloud', 'daemon', 'kick', 'kill', 'incident', 'improv', 'eviden', 'emphas', 'emphat', 'confid', 'business', 'draft', 'facilit',
    'entr', 'entrop', 'entre', 'preneur', 'entrance', 'entrant', 'entrench', 'entreat', 'entrain', 'enter', 'entertain', 'enterpris',
    'accident', 'redundan', 'ready', 'already', 'affirm', 'reduc', 'refus', 'generat', 'region', 'regist', 'implement', 'implicit', 'implicat',
    'implant', 'import', 'impress', 'pronoun', 'prompt', 'reflex', 'refin', 'regret', 'format', 'formul', 'schedul', 'fragment',
    'fract', 'fraction', 'schem', 'scholar', 'secur', 'sensor', 'sentenc', 'sharp', 'shard', 'session', 'singular', 'singl', 'sinus', 'sister',
    'skeleton', 'slight', 'watch', 'smash', 'socket', 'social', 'summit', 'trend', 'trial', 'triang', 'water', 'scenar', 'societ', 'init',
    'finish', 'finit', 'affiliat', 'infer', 'finger', 'affect', 'affin', 'infect', 'financ', 'fine', 'confin', 'currenc', 'current', 'concurr',
    'concret', 'liter', 'curio', 'recur', 'obscur', 'translat', 'rectif', 'transit', 'recurs', 'transcrib', 'transist', 'resist',
    'resilien', 'silen', 'silhouett', 'resid', 'resident', 'resonat', 'restor', 'restart', 'restat', 'restrict', 'restruct', 'submit',
    'restaurant', 'rest', 'fair', 'purchas', 'restrain', 'exploit', 'affab', 'fail', 'explod', 'result', 'resum', 'resurrect', 'host', 'grab',
    'ghost', 'hospit', 'hook', 'ordinar', 'imag', 'absorb', 'climb', 'describ', 'descen', 'condens', 'deriv', 'binanc', 'disturb', 'glob',
    'sell', 'bestow', 'best', 'beta', 'echo', 'semaphor', 'shot', 'shoot', 'short', 'screw', 'turn', 'truth', 'try', 'geo', 'sympath',
    'advanc', 'advantag', 'isolat', 'adventur', 'adorn', 'gestur', 'shift', 'shock', 'shin', 'snap', 'diminish', 'dimens', 'embod',
    'ember', 'emblem', 'deceiv', 'member', 'embrac', 'melod', 'embellish', 'emerg', 'contain', 'novel', 'novic', 'tool', 'toggl', 'token',
    'transfer', 'travel', 'travers', 'triumph', 'trivial', 'trigger', 'trim', 'troubl', 'warn', 'warm', 'warp', 'tell', 'weird', 'craft',
    'crack', 'weigh', 'weight', 'welcom', 'crash', 'bing', 'bin', 'bill', 'angl', 'boil', 'bundl', 'celebrat', 'clip', 'compensat', 'cultur',
    'consol', 'counsel', 'crawl', 'culminat', 'cull', 'storag', 'creat', 'dangl', 'spoil', 'doubl', 'dwel', 'eclips', 'ecma', 'enabl',
    'ensembl', 'tangl', 'fellow', 'gambl', 'handl', 'middl', 'model', 'modem', 'prevail', 'rambl', 'conciliat', 'recruit', 'shuffl', 'retail',
    'scrambl', 'stumbl', 'tackl', 'trail', 'trembl', 'unveil', 'cultivat', 'danger', 'engag', 'ecolog', 'emulat', 'entail', 'moderat',
    # 'shad', 'fell', 'fli', 'tang', 'tile, ->'ling', night, rect+angl, 'empt', area, ling
    'commerc', 'modern', 'comment', 'comfort', 'styl', 'stupid', 'stump', 'stun', 'instant', 'instanc', 'escalat', 'elevat', 'event',
    'evok', 'evolut', 'evolv', 'exact', 'excus', 'devolv', 'exclusiv', 'execut', 'exempl', 'escap', 'even', 'evaluat', 'estima', 'evening',
    'element', 'retriev', 'retro', 'field', 'solid', 'feel', 'till', 'distill', 'tilt', 'disabl', 'spoil', 'tunel', 'box', 'virtual',
    'list', 'limit', 'black', 'wait', 'liquidat', 'drop', 'lift', 'enlarg', 'enjoy', 'enhanc', 'fool', 'rectang', 'night', 'right',
    'bright', 'wright', 'brief', 'offer', 'coffee', 'exist', 'argument', 'fact', 'manual', 'manufactur', 'factor', 'refactor', 'manipul',
    'fear', 'feasib', 'experiment', 'export', 'desert', 'exponent', 'expound', 'explos', 'argu', 'greet', 'great', 'trad', 'half',
    'govern', 'goal', 'general', 'futur', 'further', 'fork', 'font', 'eras', 'epoch', 'episod', 'camera', 'kernel', 'keep', 'campaign',
    'eliminat', 'effort', 'eigen', 'eject', 'elaborat', 'elect', 'descript', 'degree', 'elaps', 'employ', 'envelop', 'environ', 'exceed',
    'delay', 'delet', 'delegat', 'definit', 'deliberat', 'demonstra', 'mystif', 'depreciate', 'eligib', 'elegan', 'house', 'room', 'root',
    'divers', 'diverg', 'divid', 'docker', 'dominat', 'donat', 'door', 'doom', 'camp', 'campus', 'dominan', 'boost', 'enthusiast',
    'perfect', 'person', 'perspectiv', 'persist', 'persuad', 'inherit', 'innovat', 'inspect', 'offenc', 'offens', 'offend', 'often',
    'actual', 'actuat', 'character', 'impact', 'redact', 'satellit', 'syntax', 'tranquil', 'transact', 'trajector', 'trait', 'transceiv',
    'insinuat', 'transcend', 'transclud', 'txt', 'twitter', 'tweet', 'two', 'network', 'neur', 'modul', 'twitch', 'twink', 'twin',
    'mount', 'mistak', 'moment', 'ascend', 'mountain', 'maintain', 'motiv', 'approximat', 'approb', 'motion', 'emotion', 'deform',
    'nom', 'mouse', 'merg', 'mesh', 'among', 'demand', 'match', 'amount', 'phenomen', 'gnome', 'default', 'defect', 'defeat', 'defer',
    'commiss', 'dismiss', 'emiss', 'intermiss', 'permiss', 'remiss', 'submiss', 'permanent', 'permit', 'permeat', 'defenc', 'defens',
    'defend', 'deflect', 'deflat', 'entire', 'discord', 'either', 'twiddl', 'neighbo', 'neither', 'negotiat', 'neglig', 'neglect', #'sync'
    'negativ', 'render', 'surrender', 'surround', 'surpris', 'suspend', 'surrogate', 'suspect', 'survey', 'suspens', 'surviv',# 'con'
    'deft', 'obfuscat', 'confus', 'infus', 'congratulat', 'congest', 'defus', 'infring', 'degrad', 'tensor', 'privileg', 'privat', #privacy
    'tend', 'tender', 'pretend', 'tens', 'pretens', 'pretenc', 'contend', 'contempt', 'contemplat', 'contemp', 'prior', 'threat',
    'depress', 'depriv', 'three', 'depreciat', 'tendenc', 'anonym', 'anomal', 'annual', 'mother', 'brother', 'annoy', 'announc',
    'chain', 'certain', 'annotat', 'ambigu', 'amazon', 'ambit', 'anneal', 'answer', 'afraid', 'amaz', 'ultimat', 'tweak', 'tutor',
    'tunnel', 'anim', 'reanimat', 'world', 'hello', 'analys', 'analyz', 'anchor', 'ancient', 'desk', 'correct', 'tree', 'math',
    'street', 'plot', 'material', 'imitat', 'tupl', 'imbue', 'immediat', 'immens', 'popular', 'pleas', 'populat', 'precedent',
    'menu', 'mentor', 'duck', 'dump', 'preced', 'cautio', 'dual', 'gradual', 'grad', 'upgrad', 'gradat', 'gradient', 'gradl',
    'fluctuat', 'fluen', 'fluff', 'conform', 'complian', 'flourish', 'flush', 'impertinen', 'imped', 'impend', 'impel', 'immut',
    'immers', 'imminent', 'migrat', 'industr', 'indulg', 'induct', 'induc', 'individual', 'disput', 'indent', 'incubat', 'increment',
    'decreas', 'increas', 'incredibl', 'height', 'spatial', 'final', 'filt', 'involv', 'invok', 'laugh', 'legal', 'legitim',
    'lesson', 'level', 'leverag', 'length', 'lemma', 'layer', 'play', 'splay', 'pilot', 'patch', 'platform', 'team', 'patent',
    'autonom', 'steep', 'pair', 'parallel', 'pardon', 'phras', 'passiv', 'repetit', 'php', 'storm', 'brain', 'branch', 'batch',
    'batter', 'replac', 'famil', 'battle', 'bayes', 'false', 'exult', 'extrem', 'extern', 'exterior', 'devot', 'dexter',
    'extenuat', 'extinguish', 'glyph', 'glow', 'agree', 'agitat', 'flex', 'plex', 'inflect', 'fleet', 'inflat', 'perplex',
    'multiplay', 'particip', 'particul', 'perpendicular', 'persever', 'precipit', 'precis', 'preclud', 'prolong', 'prominen', 'prolog',
    'prohibit', 'procur', 'proceed', 'procedur', 'primitiv', 'princip', 'prevent', 'presum', 'pressur', 'premis', 'preliminar',
    'prejudic', 'prais', 'possess', 'postgres', 'multipl', 'multiplatform', 'multiplex', 'multiple', 'templat', 'temperatur',
    'tempor', 'temper', 'tempt', 'truncat', 'true', 'correlat', 'correspond', 'corrupt', 'tradition', 'patien',
    'pattern', 'way', 'sway', 'ubiquit', 'impart', 'aware', 'what', 'well', 'swell', 'award', 'fascinat', 'whence', 'fashion',
    'far', 'faq', 'awak', 'awe', 'flaw', 'ware', 'while', 'insist', 'between', 'firm', 'first', 'beyond', 'betray', 'whim', 'worth',
    'wrap', 'other', 'bother', 'vocabular', 'rank', 'crank', 'shrank', 'drank', 'cramp', 'drain', 'fair', 'fare', 'brave', 'ravel',
    'breach', 'large', 'laravel', 'outlast', 'last', 'latch', 'accumulat', 'circulat', 'collat', 'conflat', 'dilat', 'laten',
    'simulat', 'stimul', 'stipulat', 'ventilat', 'violat', 'vendor', 'violen', 'lateral', 'ventur', 'colleague', 'conferenc',
    'deque', 'circuit', 'circum', 'circular', 'clear', 'clever', 'clutter', 'cling', 'citation', 'declin', 'cipher', 'cisco',
    'decimal', 'cmos', 'ascii', 'decisi', 'heuristic', 'hesitat', 'incur', 'indebt', 'indeed', 'deed', 'deduc', 'deem', 'conquer',
    'consecutiv', 'controver', 'convert', 'convex', 'convey', 'convol', 'convinc', 'corner', 'coroutin', 'core', 'soul', 'ston',
    'collinear', 'collid', 'color', 'colour', 'college', 'collung', 'arrow', 'narrow', 'narrat', 'nano', 'corollar', 'corpus',
    'cosin', 'coach', 'rapid', 'curat', 'articulat', 'cumulat', 'tabul', 'triangul', 'ransom', 'adopt', 'interact', 'interpret',
    'mutat', 'portal', 'stabl', 'integr', 'mutab', 'intercept', 'invent', 'intro', 'issu', 'pragm', 'duc', 'reduc', 'map',
    'flash', 'flat', 'flare', 'flag', 'preach', 'pray', 'pride', 'previous', 'procrastinat', 'animat', 'wound', 'angular',
    'many', 'wind', 'dwindl', 'swin', 'willing', 'swift', 'processor', 'proud', 'sock', 'provid', 'claim', 'civil', 'clamp',
    'acclaim', 'disciplin', 'accommodat', 'discern', 'competen', 'compet', 'appeas', 'protrud', 'furbish', 'appellation', 'wield',
    'whole', 'rememb', 'past', 'verb', 'advers', 'provok', 'provis', 'provocation', 'prox', 'repair', 'revok', 'reviv',
    'slot', 'slop', 'slim', 'slid', 'show', 'slic', 'slip', 'sponsor', 'split', 'splin', 'spontane', 'spread', 'speed',
    'squeez', 'sprint', 'staff', 'stemm', 'steer', 'stencil', 'bottom', 'brush', 'speculat', 'speech', 'special', 'specializ',
    'spectr', 'speci', 'spec', 'bump', 'calendar', 'calibrat', 'button', 'cable', 'burn', 'budget', 'criteri', 'credit', 'crop',
    'critique', 'crush', 'crunch', 'cub', 'lib', 'libert', 'liberal', 'libr', 'std', 'url', 'zero', 'unfurl', 'hour', 'css',
    'decen', 'liab', 'decelerat', 'diligen', 'elongat', 'else', 'elucidat', 'elud', 'embarrass', 'ensu', 'ensur', 'entangl',
    'granular', 'grace', 'grappl', 'grant', 'grand', 'gratif', 'gracious', 'disgrac', 'grate', 'gray',  'aboli', 'aggravat',
    'ablat', 'abid', 'abhor', 'abomina', 'parabol', 'paradigm', 'paragraph', 'parallax', 'parad', 'abscond', 'abrogat', 'abrupt',
    'abreast', 'acquaint', 'acquies', 'acquisition', 'knowledg', 'amus', 'amend', 'ambi', 'ambient', 'audi', 'concord',
    'conclusi', 'comprehen', 'congru', 'compound', 'aris', 'compris', 'compromis', 'compuls', 'familiar', 'famous', 'galler',
    'gallant', 'gadget', 'giant', 'gentl', 'git', 'gain', 'gift', 'girl', 'giga', 'gigant', 'grind', 'groom', 'griev', 'greed',
    'assuag', 'assum', 'assuranc', 'summon', 'assur', 'assort', 'astonish', 'astound', 'summer', 'amid', 'amiabl', 'amiss',
    'amplitud', 'android', 'anticipat', 'antenn', 'ansi', 'ansible', 'alias', 'string', 'strik', 'strip', 'substitut',
    'strid', 'striv', 'aspect', 'aspir', 'assault', 'width', 'body', 'bold', 'boast', 'anxious', 'blur', 'stretch', 'addendum',
    'substantiat', 'strong', 'widget', 'cheer', 'chief', 'child', 'summa', 'behav', 'behavio', 'behaviou', 'computer', 'intelli',
    'intellect', 'pixel', 'latitud', 'target', 'terminat','terminal', 'tera', 'term', 'termin', 'utter', 'terrain', 'mutex',
    'mutual', 'alter', 'latter', 'tentat', 'osten', 'oscill', 'oscillat', 'forth', 'hence', 'home', 'holo', 'homo', 'fatal',
    'total', 'path', 'foot', 'fortun', 'forbid', 'forum', 'enforc', 'inforc', 'forc', 'upon', 'snow', 'new', 'knock', 'neutral',
    'java', 'invit', 'includ', 'import', 'opportun', 'oppos', 'inclin', 'inclus', 'port', 'invocat', 'opponent', 'oppress',
    'coheren', 'inhibit', 'inimitab', 'disgust', 'coincid', 'cohesi', 'cognit', 'incognito', 'inherent', 'initiat',
    'ingress', 'injur', 'coin', 'innocent', 'innate', 'ingrain', 'machin', 'macro', 'magnitud', 'major', 'maneuver', 'manifest',
    'mass', 'marshall', 'mash', 'second', 'million', 'milli', 'miniatur', 'mirror', 'minus', 'minor', 'minute', 'miscellaneous',
    'mitigat', 'mix', 'mixture', 'catch', 'catalog', 'caught', 'plus', 'covet', 'plural', 'pad', 'ceas', 'ceil', 'char', 'charm',
    'charit', 'school', 'chao', 'confer', 'conduc', 'federat', 'confluen', 'confront', 'confound', 'conjectur', 'invert', 'invest',
    'investigat', 'invigorat', 'puzzl', 'shad', 'shadow', 'shak', 'sham', 'shap', 'shar', 'side', 'conjuga', 'plung', 'sick',
    'shut', 'plug', 'ping', 'chrom', 'diod', 'monitor', 'ampersand', 'alone', 'along', 'aloud', 'stall', 'stakeholder', 'forest',
    'foretell', 'forever', 'congregat', 'conniv', 'conserv', 'contingen', 'contigu', 'contour', 'contract', 'contrast', 'couch',
    'corroborat', 'cost', 'chronologic', 'pipeline', 'pitch', 'dark', 'pioneer', 'scan', 'pick', 'dart', 'valid', 'invad', 'dash',
    'frustrat', 'frustum', 'emit', 'eminen', 'epilog', 'euler', 'exclud', 'exclus', 'exercis', 'exert', 'exhibit', 'exigen',
    'eye', 'revamp', 'reveal', 'revert', 'revers', 'saas', 'scen', 'remind', 'scrap', 'secret', 'seed', 'seek', 'seduc', 'fault',
    'info', 'guid', 'raster', 'rational', 'bas', 'buil', 'bash', 'rebut', 'realm', 'recent', 'recipient', 'recept', 'reconcil',
    'record', 'recipe', 'recover', 'distribut', 'reflect', 'distress', 'regain', 'relegat', 'rent', 'recurren', 'torrent',
    'util', 'road', 'roast', 'insan', 'tax', 'took', 'volt', 'volum', 'talent', 'revolt', 'percent', 'perceiv', 'volatil', #stak
    'percept', 'paus', 'peopl', 'mission', 'transmiss', 'zoom', 'transmit', 'zon', 'cut', 'horizon', #'omi', 'coming',
    'morning', 'morrow', 'acute', 'tolerat', 'moral', 'moon', 'moor', 'tooth', 'blue', 'month', 'stag', 'lang', 'slang', 'slash',
    'only', 'errant', 'errand', 'coming', 'applaud', 'applet', 'kit', 'webinar', 'erroneous', 'apple', 'erlang', 'applianc',
    'appl', 'fire', 'myster', 'mutter', 'mut', 'natur', 'navi', 'gat', 'nativ', 'naive', 'instead', 'negat', # near nam, gon
    'institut', 'although', 'instinct', 'instigat', 'retain', 'harm', 'harness', 'instruct', 'instrument', 'insult', # by imagin
    'insuff', 'insur', 'interfac', 'interfer', 'internet', 'invers', 'transparen', 'interrupt', 'intract', 'intim',
    'intrigu', 'torch', 'topolog', 'tough', 'tout', 'transpil', 'transform', 'transgress', 'transient', 'transplant',
    'stash', 'stock', 'statistic', 'stak', 'stay', 'stationar', 'station', 'status', 'steam', 'stead', 'stand', 'stood', 'stat',
    'stud', 'stuff', 'studio', 'week', 'subscrib', 'wedg', 'strength', 'strick', 'straggl', 'stout', 'story', 'dish', 'disdain',
    'season', 'unleash', 'seat', 'law', 'mock', 'neat', 'beneath', 'bend', 'high', 'hijack', 'disk', 'wish', 'twist',
    'swish', 'swip', 'wise', 'ought', 'polar', 'bottle', 'neck', 'byte', 'kilo', 'peta', 'exaggerat', 'alert',
    'piece', 'kind', 'vexat', 'phase', 'bought', 'brought', 'apolog', 'apertur', 'bounc', 'apparent', 'huge',# 'lif', 'liv', 'lik', 'lin',
    'overlap', 'recap', 'tap', 'trap', 'trash', 'ball', 'tangent', 'apostrophe', 'anniversary', 'chunk', 'destruct',
    'accord', 'head', 'ache', 'man', 'seo', 'skip', 'impos', 'detach', 'mandat', 'impossibl', 'roman', 'accomplish',
    'reproach', 'settl', 'setup', 'woman', 'upset', 'broach', 'destroy', 'destin', 'delta', 'hub', 'act', 'delv', 'acronym',
    'arti', 'ficial', 'art', 'artist', 'quarter', 'earth', 'carv', 'cart', 'thwart', 'arrogan', 'cascad', 'apart', 'revis',
    'quarrel', 'quaternion', 'quant', 'queer', 'queen', 'thunk', 'nail', 'apache', 'bird', 'reprehen', 'apartment',
    'revisit', 'scar', 'care', 'carr', 'architect', 'archiv', 'arbit', 'arch', 'margin', 'marginal', 'area', 'scatter', 'hedron',
    'vanish', 'car', 'arduino', 'api', 'valu', 'vector', 'eight', 'for', 'app', 'apposit', 'entrap', 'dream', 'dron', 'drill',
    'octa', 'dub', 'dress', 'driv', 'drink', 'talk', 'tall', 'drag', 'engross', 'entitl', 'eradicate', 'litera', 'obliterat',
    'plac', 'display', 'plain', 'planar', 'plan', 'plane', 'planet', 'complacen', 'bulk', 'buch', 'buy', 'calm', 'off', 'take',
    'tak', 'tag', 'tailor', 'tail', 'oust', 'one', 'noone', 'honest', 'noone', 'demot', 'curtail', 'bone', 'demo', 'cone',
    'honour', 'postpon', 'patron', 'cursor', 'demolish', 'pump', 'snip', 'punct', 'long', 'sniff', 'punish', 'pupil', 'mongo',
    'humour', 'journal', 'journ', 'pour', 'humbl', 'park', 'rumour', 'pin', 'joy', 'scal', 'scalar', 'sys', 'much',
    'inaugurat', 'mon', 'favo', 'endeav', 'labo', 'laborator', 'collaborat', 'lab', 'lack', 'cold', 'fus', 'scold', 'idiom', 'axiom',
    'matur', 'matter', 'premier', 'four', 'splend', 'stair', 'chair', 'http', 'url', 'html', 'aim', 'air', 'conspir', 'fortif',
    'fac', 'tun', 'treat', 'cris', 'attribut', 'attract', 'intuit', 'intrusiv', 'inur', 'couth', 'fragil', 'aghast', 'outer',
    'agil', 'outrage', 'lonel', 'clog', 'relish', 'littl', 'ugl', 'benefit', 'fad', 'bent', 'bend', 'bereav', 'bereft', 'fit', 'sorry',
    'miser', 'commiserat', 'abstract', 'abundan', 'abstain', 'been', 'fidget', 'fide', 'account', 'adher', 'adjacen', 'adjectiv',
    'ador', 'arm', 'win', 'alarm', 'earl', 'skew', 'year', 'yeah', 'window', 'loyal', 'yellow', 'blow', 'scrut', 'scrup', 'shallow',
    'darl', 'blind', 'mid', 'might', 'timid', 'bless', 'blend', 'blank', 'wav', 'blam', 'tabl', 'refut', 'scrutiniz', 'titl', 'youth',
    'forge', 'forget', 'forgiv', 'palette', 'panel', 'abat', 'item', 'men', 'human', 'site', 'pag', 'tremend', 'comma', 'obstacl',
    'vue', 'nam', 'cod', 'tour', 'tournament', 'edge', 'vulgar', 'accrue', 'accus', 'ada', 'ful', 'glimps', 'plent', 'pledg',
    'wizard', 'power', 'relinquish', 'reliev', 'ornament', 'dia', 'gonal', 'dialect', 'dialog', 'dial', 'meter', 'nurs', 'jitter',
    'writ', 'wrote', 'wretch', 'relax', 'fulfil', 'file', 'dos', 'sincere', 'since', 'figur', 'layout', 'dot', 'bot', 'both', 'fight',
    'fuel', 'get', 'lay', 'laid', 'twent', 'underwent', 'went', 'twelve', 'whelm', 'simultaneous', 'similar', 'silver', 'odd',
    'signal', 'signif', 'signatur', 'dissent', 'dissipat', 'sociat', 'disrupt', 'dissuad', 'distan', 'tast', 'taught', 'speak', 'spoke',
    'fram', 'framework', 'guard', 'wire', 'tim', 'verbos', 'obstinate', 'obtain', 'obviat', 'obvious', 'occasion', 'occup', 'occlud',
    'obstruct', 'old', 'omit', 'hold', 'gold', 'thres', 'got', 'vigour', 'django', 'rigorous', 'logit', 'logistic', 'gorgeous', 'poll',
    'during', 'duration', 'durab', 'notat', 'cur', 'curl', 'light', 'male', 'female', 'equaliz', 'linguist', 'compel', 'sill',
    'mak', 'made', 'get', 'hav', 'has', 'haskell', 'captcha', 'hast', 'hassl', 'haunt', 'hunt', 'hurr', 'lodg', 'loose', 'lov', 'loud',
    'low', 'luxur', 'mama', 'marr', 'indign', 'meet', 'meditat', 'merit', 'messag', 'demodulat', 'late', 'option', 'outage', 'overrid',
    'saturat', 'frantic', 'warrant', 'endur', 'rand', 'fortran', 'fragran', 'hinder', 'intra', 'vibr', 'remonstra', 'bring', 'brisk',
    'wash', 'franca', 'him', 'hint', 'hindranc', 'remembr', 'ramp', 'hir', 'thir', 'think', 'they', 'theta', 'tolera', 'ther', 'thest',
    'whip', 'whisp', 'thither', 'thin', 'hist', 'retir', 'until', 'retent', 'told', 'those', 'thous', 'therm', 'thes', 'away', 'thesa',
    'fraud', 'rather', 'father', 'ran', 'ratio', 'illustrat', 'tether', 'aberrant', 'encumb', 'penetrat', 'forb', 'illuminat', 'illus',
    'foray', 'giv', 'glad', 'glanc', 'farth', 'ether', 'numb', 'net', 'auth', 'glass', 'conviv', 'conv', 'dang', 'obey', 'genuin',
    'geni', 'gener', 'heather', 'heat', 'heaven', 'dinner', 'heav', 'contrit', 'attrit', 'happen', 'heart', 'held', 'heir', 'vigorous',
    'log', 'thriv', 'cas', 'thrill', 'came', 'witness', 'threw', 'thrift', 'lend', 'lent', 'relent', 'insolen', 'indolen', 'inso',
    'jealous', 'jet', 'jok', 'job', 'judg', 'kept', 'rais', 'diffiden', 'juggl', 'kept', 'rain', 'rac', 'rad', 'brag', 'brac', 'boy',
    'surg', 'sync', 'surfac', 'surf', 'surmis', 'untaint', 'surpass', 'risk', 'rival', 'ris', 'rose', 'river', 'village', 'town', 'worr',
    'see', 'saw', 'seen', 'sees', 'sawed', 'sawn', 'noun', 'sav', 'gam', 'notorious', 'nought', 'gap', 'mile', 'ston', 'smil', 'smell',
    'smok', 'mild', 'segue', 'send', 'sent', 'senior', 'sensation', 'seven', 'several', 'sever', 'shrink', 'shrank', 'shrunk', 'sigh',
    'sink', 'six', 'situat', 'slav', 'sleep', 'slept', 'sembl', 'solution', 'sensitiv', 'assent', 'seiz', 'seminar', 'slay', 'smit',
    'seldom', 'spam', 'span', 'spel', 'spen', 'spring', 'winter', 'subtl', 'subtract', 'such', 'wip', 'sudden', 'sprinkl', 'suffer',
    'suffix', 'suppress', 'sure', 'synthes', 'tear', 'teas', 'tenacious', 'terribl', 'terrif', 'reluctan', 'now', 'dissonan', 'song',
    'json', 'consonan', 'concis', 'go', 'ago', 'had', 'hadoop', 'line', 'inlin', 'lingu', 'ink', 'inner', 'tinker', 'begin', 'began',
    'begun', 'lead', 'leak', 'lect', 'leav', 'legend', 'lens', 'left', 'let', 'plead', 'leas', 'mat', 'lean', 'bleak', 'leaf', 'plent',
    'deplet', 'replet', 'doat', 'liv', 'lik', 'til', 'hack', 'tight', 'drown', 'drunk', 'contr', 'drew', 'ear', 'earn', 'eas', 'eat',
    'eager', 'near', 'dear', 'hex', 'sea', 'seal', 'who', 'whop', 'whither', 'why', 'peripher', 'wick', 'wide', 'perl', 'heter', 'hit',
    'hither', 'hit', 'hiv', 'hi', 'hid', 'hiber', 'delphi', 'chin', 'behind', 'nourish', 'whilst', 'phish', 'poach', 'pocket', 'publish',
    'puff', 'prov', 'podcast', 'pod', 'her', 'propriet', 'incept', 'strat', 'grat', 'stray', 'raspberry', 'rar', 'congrat', #'rat',
    'scratch', 'raptur', 'instat', 'ubuntu', 'nois', 'para', 'persuas', 'pertain', 'pervad', 'pertin', 'pessimi', 'pos', 'typo',
    # 'how',#'nomin',#'rat',
    'october', 'december', 'june', 'july', 'august', 'september', 'november', 'march', 'february', 'april', 'january', 'haul',
    'poor', 'pros', 'prospect', 'revel', 'rush', 'salar', 'spar', 'spark', 'genet', 'spawn', 'treasur', 'spirit', 'big', 'tip', 'inno',
    'tread', 'trifl', 'vouch', 'vot', 'volunt', 'spit', 'bit', 'habit', 'zip', 'hop', 'hook', 'chop', 'chose', 'walk', 'wak', 'nerv',
    'ingrat', 'conclud', 'during', 'ingest', 'date', 'dat', 'commend', 'daughter', 'commenc', 'daunt', 'ingen', 'dawdl', 'predecess',
    'concess', 'damp', 'danc', 'dabbl', 'dar', 'lidar', '.js', 'ddr', 'preserv', 'prepend', 'prett', 'primar', 'lanc', 'knew', 'king',
    'intend', 'intens', 'intent', 'peak', 'peac', 'wreak', 'lurk', 'trunk', 'truncat', 'peculiar', 'peer', 'peek', 'peep', 'penal',
    'alex', 'amper', 'asham', 'ampl', 'aside', 'am', 'jam', 'always', 'flam', 'sdk', 'slack', 'skype', 'drank', 'temp', 'slack', 'scream',
    'slam', 'preambl', 'lambd', 'roam', 'ram', 'dram', 'saf', 'safar', 'sal', 'revolv', 'siz', 'sad', 'hood', 'impl', 'impet', 'rear',
    'rearrang', 'rely', 'rescind', 'pur', 'syllabl', 'swoop', 'tier', 'top', 'blew', 'badg', 'bad', 'bag', 'garment', 'garbag',
    'bow', 'bowl', 'bridg', 'broke', 'btw', 'bye', 'clue', 'club', 'collud', 'collis', 'column', 'compliment', 'compli', 'comply',
    'conceal', 'conced', 'concav', 'conceit', 'divert', 'divis', 'div', 'due', 'dull', 'dust', 'empt', 'exempt', 'reset', 'offset',
    'pen', 'pencil', 'pend', 'spend', 'pens', 'pent', 'transcript', 'transduc', 'transduct', 'transliterat', 'clobber', 'asset', 'assid',
    'rat', 'reliab', 'relian', 'remed', 'nominal', 'nod', 'how', 'hover', 'nine', 'nice', 'mechan', 'meddl', 'matrimon', 'max', 'felt',
    'urg', 'urban', 'very', 'virus', 'vulner', 'waiv', 'wander', 'war', 'wast', 'weak', 'west', 'widow', 'wood', 'yes', 'yet', 'yield',
    'wor', 'woke', 'whirl', 'weld', 'xml', 'vanit', 'vacan', 'vague', 'ceremon', 'unar', 'symmetr', 'subject', 'ordinat', 'stir',
    'stoop', 'strok', 'shoe', 'bar', 'ban', 'keen', 'banish', 'tedious', 'technolog', 'techni', 'bisect', 'theft', 'thaw', 'flurr',
    'third', 'thirt', 'thousand', 'wont', 'beat', 'vaunt', 'fumbl', 'fungib', 'blunt', 'bunch', 'conundrum', 'punk', 'flung', 'funnel',
    'etc', 'euro', 'crim', 'hung', 'hundred', 'saunter', 'satur', 'sauc', 'sun', 'junk', 'furcat', 'junior', 'slumber', 'sling',
    'pronunc', 'sung', 'sunk', 'smack', 'sly', 'swung', 'bear', 'bucket', 'vast', 'beam', 'sang', 'sank', 'slung', 'slugg', 'sanit',
    'substan', 'subsid', 'subsist', 'listen', 'llm', 'llama', 'loom', 'llvm', 'bloom', 'blossom', 'glor', 'gloss', 'gloom',
    'mem', 'mod', 'bus', 'modest', 'motor', 'motivat', 'mov', 'burst', 'bur', 'imburs', 'mull', 'uous', 'conspic', 'stren', 'ardent',
    'arduous', 'samsung', 'ops', 'pop', 'dev', 'devis', 'deviat', 'detract', 'devoid', 'opaque', 'opaci', 'devalu', 'devastat', 'azure',
    'averag', 'avatar', 'avert', 'autumn', 'associat', 'auxiliar', 'aton', 'atlas', 'boss', 'jira', 'jinja', 'add', 'addit', 'adept',
    'jott', 'jut', 'kotlin', 'kubernet', 'jdo', 'jest', 'dom', 'majest', 'jdk', 'jvm', 'jre', 'jwt', 'dbc', 'jpg', 'jpeg',
    'legac', 'legib', 'discount', 'discourag', 'discreet', 'led', 'amo', 'assail', 'crumbl', 'leap', 'baffl', 'flav', 'fixat',
    'flew', 'flee', 'fled', 'fling', 'flirt', 'fly', 'focal', 'flutter', 'fli', 'afflict', 'affix', 'floor', 'flopp', 'five', 'flask',
    'alternat', 'agent', 'agglomerat', 'agenc', 'agenda', 'again', 'against', 'volub', 'usb', 'blob', 'alike', 'alive', 'usab', 'usag',
    'tir', 'tiny', 'case', 'summ', 'succinct', 'stagnat', 'inst', 'instabil', 'upper', 'upped', 'geek', 'radio', 'raid', 'rail',
    'supper', 'dusk', 'dut', 'duo', 'dup', 'vis', 'lavish', 'entit', 'entic', 'jenkins', 'knack', 'keras', 'rag', 'gemini', 'ruby',
    'rude', 'crucial', 'prun', 'obtrud', 'pruden', 'impuls', 'rubber', 'upbraid', 'rudimen', 'rugged', 'latin', 'impuden', 'crude',
    'impur', 'imput', 'lag', 'lap', 'laps', 'scap', 'lan', 'lash', 'splash', 'plagued', 'clash', 'clarity', 'laz', 'leverat',
    'nlp', 'non', 'noname', 'nonsens', 'murmur', 'nltk', 'meal', 'met', 'metal', 'mere', 'esteem', 'wasm', 'meld', 'melanchol',
    'spac', 'mercant', 'merchan', 'estate', 'scrab', 'rough', 'rous', 'rol', 'rock', 'onerous', 'rnn', 'rimm', 'rip', 'rid',
    'rgb', 'ridd', 'revenue', 'request', 'repl', 'fri', 'grip', 'horribl', 'horror', 'hybrid', 'husband', 'hype', 'repla',
    'replenish', 'reput', 'reputa', 'rigid', 'star', 'pursu', 'receipt', 'tamper', 'tam', 'tap', 'sue', 'steal', 'stale', 'stare',
    'groov', 'recaptur', 'opt', 'oracle', 'dbms', 'rust', 'sail', 'said', 'scrum', 'tripl', 'theorem', 'lace', 'enough',
    'solace', 'guest', 'gui', 'sold', 'software', 'solely', 'solemn', 'fatig', 'fat', 'fanc', 'fan', 'entrust', 'enum', 'enumer',
    'envi', 'envision', 'extravagan', 'flight', 'ftp', 'glue', 'glitch', 'impersonat', 'quiz', 'raw', 'ray', 'gcc', 'gave',
    'forfeit', 'hail', 'halt', 'hamper', 'guilt', 'hackathon', 'harsh', 'impair', 'flux', 'gnu', 'lie', 'licentious', 'gpt',
    'gpu', 'cpu', 'gps', 'mvp', 'mvc', 'optimiz', 'optimal', 'lstm', 'cbow', 'deput', 'decorat', 'bonus', 'bond', 'condemn',
    'decad', 'decay', 'deceit', 'decrement', 'fake', 'faint', 'fame', 'feebl', 'federal', 'fond', 'food', 'foll', 'forebod',
    'froz', 'frugal', 'fun', 'gaz', 'gaug', 'gig', 'glean', 'glee', 'glar', 'goto', 'grav', 'gravit', 'grep', 'grew', 'gist',
    'grudg', 'gruel', 'grunt', 'gsm', 'grpc', 'disguis', 'hat', 'hazard', 'hdd', 'hdmi', 'holi', 'holistic', 'homogen', 'idol',
    'inch', 'incent', 'incit', 'enchant', 'encapsulat', 'endors', 'enem', 'enroll', 'evaporat', 'evas', 'fasten', 'feet', 'fell',
    'few', 'festiv', 'fenc', 'fidel', 'fickl', 'fift', 'fish', 'find', 'fir', 'fin', 'evad', 'fees', 'fox', 'fend', 'fought',
    'forgot', 'fuzz', 'game', 'gen', 'gem', 'gan', 'cuda', 'gramm', 'elde', 'efficien', 'ebriet', 'lumin', 'croach', 'pedia',
    'mac', 'wifi', 'suprem', 'mad', 'wife', 'elusiv', 'set', 'rul', 'ruin', 'rumor', 'heal', 'especial', 'escort', 'essential',
    'extricat', 'fabl', 'fastidious', 'femin', 'feign', 'forgav', 'forgo', 'quint', 'formaliz', 'formulat', 'refrain', 'gauss',
    'euclid', 'gb', 'asm', 'jasmin', 'asp', 'grasp', 'asper', 'fps', 'input', 'ascrib', 'asap', 'ascertain', 'async', 'ascent',
    'asymmetr', 'astray', 'asunder', 'cooperat', 'copy', 'copi', 'crav', 'decentraliz', 'concert', 'indelibl', 'fopp', 'imagin',
    'uniform', 'utmost', 'utf', 'viral', 'virtue', 'vertex', 'version', 'versus', 'versa', 'veri', 'verity', 'via', 'vib',
    'vgg', 'vga', 'venue', 'valley', 'vain', 'vacat', 'vagar', 'svd', 'svg', 'svm', 'svn', 'ux', 'tru', 'linux', 'redux',
    'strov', 'crux', 'jupyter', 'soup', 'drupal', 'dry', 'cry', 'crystal', 'tea', 'hot', 'shy', 'becom', 'became', 'beside',
    'bert', 'brak', 'beg', 'bat', 'combat', 'perturb', 'basis', 'perus', 'awful', 'awk', 'axis', 'axes', 'cad', 'brack', 'comfy',
    'nominat', 'normaliz', 'reckon', 'north', 'east', 'south', 'prosper', 'typ', 'shall', 'sci', 'sky', 'sneer', 'sober',
    'solitar', 'student', 'tab', 'pip', 'pipe', 'stab', 'pit', 'son', 'languag', 'marriag', 'packag', 'patronag', 'passag',
    'congress', 'congruent', 'paid', 'cron', 'crm', 'sit', 'requisit', 'adware', 'affair', 'cli', 'aws', 'bios', 'cmd', 'cms',
    'cnn', 'cobol', 'cocoa', 'coaxial', 'allianc', 'angel', 'attenuat', 'brevity', 'apt', 'candidat', 'canvas', 'dig', 'dilut',
    'dignit', 'aptly', 'anew', 'candid', 'despit', 'plausib', 'clause', 'creden', 'credib', 'cri', 'descri', 'ajax', 'aka',
    'alacrit', 'alack', 'differentia', 'die', 'dirt', 'dire', 'domestic', 'doth', 'dread', 'return', 'river', 'obedien', 'dole',
    'sgd', 'sex', 'shelter', 'shed', 'row', 'condolenc', 'rpc', 'rsa', 'rpg', 'rss', 'rtti', 'rue', 'shook', 'sleek', 'slew',
    'sleet', 'sneak', 'soar', 'soap', 'hereby', 'thereby', 'standby', 'by', 'of', 'poem', 'oem', 'ref', 'val', 'interval',
    'refresh', 'refund', 'refocus', 'reform', 'reformat', 'reformulat', 'refract', 'refurbish', 'refit', 'refill', 'refil',
    'refetch', 'cofound', 'interven', 'crypto', 'into', 'joomla', 'kanban', 'kde', 'concentrat', 'kivy', 'lda', 'money', 'once',
    'exit', 'exhaust', 'your', 'youtub', 'yaml', 'wors', 'x86', 'x64', 'women', 'within', 'without', 'gem', 'worship', 'won',
    'tong', 'turbo', 'uint', 'radius', 'rall', 'radiat',
    #'sit', worfklow, retargatable, disc, at, ace, lumin++, croach++, cry++, in, out, servicedesk, autodesk
    # rat, tri, son, perma-link neura-link euclid tip bi- , hit,
    #'ling', #'lin', # 'gap', 'eag', 'tim' ring,
    #'out', 'our', 'mon', lin lif liv pace
    #'emplace',
    # er?, gence, gance, que, marathon fulltime
    # 'summar', 'summat',
    #repo, rand,
    #act, bas, log,
    #url, exe, ecut, net, non, sum, go, act, add, app, plac, tun,
    ]


if __name__ == '__main__':

    vocab = sorted(diixo)

    print(f"sz={len(vocab)}")

    with open("tokens.txt", "w", encoding="utf-8") as f_out:
        for word in vocab:
            f_out.write(f"{word}\n")
